language: generic 

sudo: required
services: 
  - docker
  
before_install:
  - docker build -t loconluis/docker-devworkflow-react -f Dockerfile.dev .

script:
  - docker run -e CI=true loconluis/docker-devworkflow-react npm run test
